# Generated by Django 4.1.2 on 2023-01-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('employer', 'Employer')], default='agent', max_length=250, verbose_name='Account Type'),
        ),
    ]
