# Generated by Django 4.1.2 on 2023-01-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('employer', 'Employer')], default='employer', max_length=250, verbose_name='Account Type'),
        ),
    ]
