# Generated by Django 4.1.2 on 2022-12-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=5000)),
                ('firstname', models.CharField(max_length=5000)),
                ('lastname', models.CharField(max_length=5000)),
                ('phone', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
