# Generated by Django 4.1.2 on 2022-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0002_employer_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='passwd',
            field=models.CharField(default='indegepass', max_length=5000),
        ),
    ]
