# Generated by Django 4.1.2 on 2022-12-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0003_employer_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='passwd',
            field=models.CharField(default='IDGPASS', max_length=5000),
        ),
    ]
