# Generated by Django 4.1.2 on 2023-01-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0005_alter_employer_passwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='passwd',
            new_name='password',
        ),
    ]
