# Generated by Django 4.1.2 on 2023-01-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0007_jobseeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='username',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
