# Generated by Django 4.1.2 on 2023-01-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0009_alter_jobseeker_gender_alter_jobseeker_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='other_job',
            field=models.TextField(null=True),
        ),
    ]
