# Generated by Django 4.1.2 on 2023-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0010_alter_jobseeker_other_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfidcard',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
