# Generated by Django 4.1.2 on 2023-01-02 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0011_rfidcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidcard',
            name='time',
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
