# Generated by Django 4.1.2 on 2023-01-05 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0014_remove_contact_id_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidcard',
            name='date',
        ),
        migrations.AddField(
            model_name='rfidcard',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
