# Generated by Django 4.1.2 on 2023-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0016_present_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present_worker',
            name='arrival_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
