# Generated by Django 4.1.2 on 2023-01-06 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0017_alter_present_worker_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present_worker',
            name='arrival_time',
        ),
        migrations.AddField(
            model_name='present_worker',
            name='date_arrived',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
