# Generated by Django 4.1.2 on 2023-01-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0018_remove_present_worker_arrival_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
