# Generated by Django 4.1.2 on 2023-01-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0019_delete_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='job_type',
            new_name='work_type',
        ),
    ]
