# Generated by Django 4.1.2 on 2023-01-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0020_rename_job_type_jobseeker_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='password',
        ),
    ]
