# Generated by Django 4.1.2 on 2023-01-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkerapp', '0022_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
