# Generated by Django 4.1.2 on 2023-01-08 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkerapp', '0023_delete_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=5000)),
                ('lastname', models.CharField(max_length=5000)),
                ('phone', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=5000)),
                ('password', models.CharField(max_length=5000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
